name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: interview-to-user-stories
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
    
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Authorize Docker push
      run: gcloud auth configure-docker
    
    - name: Build and Deploy Backend
      run: |
        gcloud builds submit --config cloudbuild.yaml .
    
    - name: Get Backend URL
      id: backend-url
      run: |
        BACKEND_URL=$(gcloud run services describe interview-etl-backend --region=$REGION --format='value(status.url)')
        echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT
    
    - name: Comment Backend URL
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 Backend deployed successfully!\n\n**Backend URL:** ${{ steps.backend-url.outputs.url }}\n\n**Next Steps:**\n1. Update your frontend environment with this URL\n2. Test the API endpoints\n3. Process your interview transcripts!`
          })
      if: github.event_name == 'pull_request'
